name: Update Crypto Data

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests gspread oauth2client

      - name: Debug Secret Value (Masked in log)
        run: |
          echo "==> START SECRET VALUE"
          echo "${{ secrets.GCP_CREDENTIALS }}"
          echo "==> END SECRET VALUE"

      - name: Write creds.json
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > creds.json
          echo "==> creds.json written"
          cat creds.json | head -n 5

      - name: Confirm file exists
        run: |
          ls -la
          cat creds.json | jq '.' || echo "Invalid JSON!"

      - name: Run script
        run: python update_crypto_sheet.py